import assert from 'node:assert/strict';
import { financeSummary, goalSavingsPlan, contributeToGoal } from '../utils/financeSummary';
import { applyCapturedPayments } from '../utils/capturedPayments';
import { pendingDebitReasons } from '../utils/debitReasons';
import type { Expense, IncomeEntry, PaymentReview, AutoExpense } from '../context/AppContext';
import type { CapturedPayment, DebitReasonReply } from '../utils/paymentModels';

const state={profile:{name:'Arun',username:'arun',monthlySalary:50000,yearlySalary:600000,otherIncome:0,currentSavings:20000,onboardingComplete:true},incomes:[] as IncomeEntry[],expenses:[12000,8000,3000,4000,2500].map((amount,i)=>({id:`expense-${i}`,date:'2026-10-08',amount,category:'Others',paymentType:'Cash'} as Expense)),autoExpenses:[] as AutoExpense[],paymentReviews:[] as PaymentReview[],capturedIds:[] as string[],goals:[{id:'villa',name:'Villa',targetAmount:10000000,savedAmount:5000,targetDate:'2027-10-08'},{id:'car',name:'Family Car',targetAmount:1800000,savedAmount:3000},{id:'bike',name:'Dream Bike',targetAmount:250000,savedAmount:2000}]};
const summary=financeSummary(state,'2026-10');
assert.equal(summary.balance,40500);
assert.equal(summary.availableBalance,30500);
assert.equal(summary.monthlySurplus,20500);
assert.equal(goalSavingsPlan(state.goals[0],summary.monthlySurplus,'2026-10-08').affordable,false);
assert.equal(goalSavingsPlan(state.goals[1],summary.monthlySurplus,'2026-10-08').monthlyAmount,4100);
assert.equal(contributeToGoal(state,'bike',40000,'2026-10'),state);
const timestamp=new Date(2026,9,8,12).getTime();
const credits:CapturedPayment[]=[10000,20000].map((amount,i)=>({id:`credit-${i}`,amount,kind:'income',source:'com.sbi.SBIFreedomPlus',timestamp}));
const credited=applyCapturedPayments(state,credits);
assert.equal(financeSummary(credited,'2026-10').balance,70500);
assert.equal(financeSummary(credited,'2026-10').availableBalance,60500);
const debit:CapturedPayment={id:'debit',amount:1500,kind:'expense',source:'com.sbi.SBIFreedomPlus',timestamp};
const spent=applyCapturedPayments(credited,[debit]);
assert.equal(financeSummary(spent,'2026-10').balance,69000);
assert.equal(pendingDebitReasons(spent.expenses).length,1);
const reply:DebitReasonReply={id:'reply-debit',captureId:'debit',kind:'reason',reason:' Groceries ',timestamp};
const named=applyCapturedPayments(spent,[reply,reply]);
assert.equal(named.expenses[0].notes,'Groceries');
assert.equal(named.expenses[0].amount,1500);
assert.equal(pendingDebitReasons(named.expenses).length,0);
assert.equal(financeSummary(named,'2026-10').balance,69000);
assert.equal(applyCapturedPayments(JSON.parse(JSON.stringify(named)),[...credits,debit,reply]).expenses.length,6);
assert.equal(applyCapturedPayments(state,[reply]),state,'early reply must be retained for a later import');
assert.equal(applyCapturedPayments({...spent,expenses:state.expenses},[reply]).expenses.length,5,'reply must not recreate a deleted debit');
for(const reason of ['', ' ', 'x'.repeat(201)]) assert.equal(applyCapturedPayments(spent,[{...reply,reason}]),spent);
const salary=applyCapturedPayments(named,[{...credits[0],id:'salary',amount:50000}]);
const classified={...salary,incomes:salary.incomes.map(e=>e.id==='salary'?{...e,category:'Salary'}:e)};
assert.equal(financeSummary(classified,'2026-10').balance,69000,'salary must not count twice');
console.log('Household scenario passed: villa/car/bike, 40,500 balance, 10k + 20k credits => 70,500, debit => 69,000, inline reply, replay and salary deduplication.');
